name: cloud front invalidator
on : [push]
jobs:
    build-app:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: frontend
        steps:
            - uses: actions/checkout@v4 #clone repo
            - uses: actions/setup-node@v4 #setup nodejs
              with:
                node-version: '18.15.0'
            - run : tree
            - name: 'Install deps'
              run: npm install
            - name: 'Build the Project'
              run: npm run build

    